Fix some syntax errors

diff --git a/check_phishtank b/check_phishtank
--- a/check_phishtank
+++ b/check_phishtank
@@ -6,52 +6,46 @@ file_expiry_mins=60
 search_string=$1
 phishtank_api_key="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 
-# stop on errors
-#set -e
-
-# file locking, so we don't re-download if being called repeatedly
-scriptname=$(basename $0)
-pidfile="/var/run/${scriptname}"
-exec 200>$pidfile
-flock -x 200 
-pid=$$
-echo $pid 1>&200
-
 # first see if the file exists, and if so, if it is stale
 if [ -f $tmp_folder/$file_name ]
 then
-	echo "file exists..."
-	file_expired=$( find $tmp_folder/$file_name -mmin +$file_expiry_mins | egrep '.*' )
+        # echo "file exists..."
+        file_expired=$( find $tmp_folder/$file_name -mmin +$file_expiry_mins | egrep '.*' )
 else
-	echo "file not present..."
-	file_expired=true
+#       echo "file not present..."
+        file_expired=true
 fi
 
 # if the file needs to be (re)downloaded, do so
 if [ $file_expired ]
 then
-	echo "file expired...refreshing..."
-	wget -O $tmp_folder/$file_name".bz2" "http://data.phishtank.com/data/$phishtank_api_key/online-valid.csv.bz2"
-	if [[ $? -ne 0 ]]; then
-		echo "UNKNOWN- unable to download Phishtank file"
-		rm $tmp_folder/$file_name".bz2"
-		exit 3
-	else
-		bunzip2 -f $tmp_folder/$file_name".bz2"
-		if [[ $? -ne 0 ]]; then
-			echo "UNKNOWN- unable to bunzip2 Phishtank file" 
-			exit 3
-		fi
-	fi
+        #echo "file expired...refreshing..."
+        wget -q -O $tmp_folder/$file_name".bz2" 'http://data.phishtank.com/data/$phishtank_api_key/online-valid.csv.bz2'
+        if [[ $? -ne 0 ]]; then
+                echo "UNKNOWN: unable to download Phishtank file"
+                rm $tmp_folder/$file_name".bz2"
+                exit 3
+        else
+                bunzip2 -q -f $tmp_folder/$file_name".bz2"
+                if [[ $? -ne 0 ]]; then
+                        echo "UNKNOWN: unable to bunzip2 Phishtank file"
+                        exit 3
+                fi
+        fi
 fi
 
 # check for badness
-echo "looking for $search_string"
-grep -l $search_string $tmp_folder/$file_name 
-if [[ $? == 1 ]]; then 
-	echo "OK- $search_string"
-	exit 0
+grep -l $search_string $tmp_folder/$file_name
+
+if [ $? != 1 ];
+then
+        output=$(grep $search_string $tmp_folder/$file_name)
+        echo "CRITICAL: $search_string - $output"
+        exit 2
 else
-	output=$(grep $search_string $tmp_folder/$file_name)
-	echo "CRITICAL- $search_string - $output"
+        echo "OK: $search_string"
+        exit 0
 fi
+
+echo "UNKNOWN: Should never have reached this point"
+exit 3
